//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDADES_TIPO_RECOGIDAS
    {
        public System.Guid ID { get; set; }
        public string IDCIUDAD { get; set; }
        public int IDTIPORECOGIDA { get; set; }
        public Nullable<int> LIMITE { get; set; }
        public Nullable<int> DIAS_ELIMINACION { get; set; }
        public Nullable<int> DIAS_FINALIZACION { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual TIPO_RECOGIDAS TIPO_RECOGIDAS { get; set; }
    }
}
