//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION_EXCEL
    {
        public System.Guid ID { get; set; }
        public string IDCIUDAD { get; set; }
        public int IDTIPO_RECOGIDA { get; set; }
        public string NOMBRE_CAMPO { get; set; }
        public int COLUMNA_CAMPO { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual TIPO_RECOGIDAS TIPO_RECOGIDAS { get; set; }
    }
}
