//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTANCIAS
    {
        public System.Guid ID_ORIGEN { get; set; }
        public System.Guid ID_DESTINO { get; set; }
        public Nullable<double> DISTANCIA { get; set; }
        public Nullable<double> TIEMPO { get; set; }
    
        public virtual PUNTOS_RUTA PUNTOS_RUTA { get; set; }
        public virtual PUNTOS_RUTA PUNTOS_RUTA1 { get; set; }
    }
}
