//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURACION
    {
        public System.Guid ID { get; set; }
        public string IDCIUDAD { get; set; }
        public Nullable<int> IDTIPORUTA { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> NUMERO_PUNTOS { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual TIPO_RECOGIDAS TIPO_RECOGIDAS { get; set; }
    }
}
