//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTOS_RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUNTOS_RUTA()
        {
            this.DISTANCIAS = new HashSet<DISTANCIAS>();
            this.DISTANCIAS1 = new HashSet<DISTANCIAS>();
        }
    
        public System.Guid ID { get; set; }
        public string IDCIUDAD { get; set; }
        public System.Guid IDRUTA { get; set; }
        public string CODIGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_DEMANDA { get; set; }
        public string DESCRIPCION { get; set; }
        public string LOCALIZACION { get; set; }
        public string OBSERVACIONES { get; set; }
        public int IDESTADO { get; set; }
        public string LONGITUD { get; set; }
        public string LATITUD { get; set; }
        public bool ELIMINADO { get; set; }
        public Nullable<int> ITINERARIO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<bool> COORDENADAS_CALCUDADAS { get; set; }
        public Nullable<bool> DISTANCIAS_CALCUDADAS { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual ESTADOS_PUNTOS ESTADOS_PUNTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTANCIAS> DISTANCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTANCIAS> DISTANCIAS1 { get; set; }
        public virtual PUNTOS_RUTA PUNTOS_RUTA1 { get; set; }
        public virtual PUNTOS_RUTA PUNTOS_RUTA2 { get; set; }
        public virtual RUTAS RUTAS { get; set; }
    }
}
