//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUTAS()
        {
            this.HISTORIAL = new HashSet<HISTORIAL>();
            this.PUNTOS_RUTA = new HashSet<PUNTOS_RUTA>();
        }
    
        public System.Guid ID { get; set; }
        public string IDCIUDAD { get; set; }
        public int IDTIPORECOGIDA { get; set; }
        public int IDESTADO { get; set; }
        public int NUMERO_PUNTOS { get; set; }
        public string ARCHIVO_ORIGEN { get; set; }
        public System.Guid IDUSUARIO { get; set; }
        public System.DateTime FECHA_INCORPORACION { get; set; }
        public Nullable<System.DateTime> FECHA_OPTIMIZACIÓN { get; set; }
        public Nullable<bool> FACTURADA { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL> HISTORIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTOS_RUTA> PUNTOS_RUTA { get; set; }
        public virtual TIPO_RECOGIDAS TIPO_RECOGIDAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
