//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSWR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWREntities : DbContext
    {
        public SWREntities()
            : base("name=SWREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<CIUDADES_TIPO_RECOGIDAS> CIUDADES_TIPO_RECOGIDAS { get; set; }
        public virtual DbSet<CONFIGURACION_EXCEL> CONFIGURACION_EXCEL { get; set; }
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<ESTADOS> ESTADOS { get; set; }
        public virtual DbSet<ESTADOS_PUNTOS> ESTADOS_PUNTOS { get; set; }
        public virtual DbSet<FACTURACION> FACTURACION { get; set; }
        public virtual DbSet<HISTORIAL> HISTORIAL { get; set; }
        public virtual DbSet<PAISES> PAISES { get; set; }
        public virtual DbSet<PUNTOS_RUTA> PUNTOS_RUTA { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<RUTAS> RUTAS { get; set; }
        public virtual DbSet<TARIFAS> TARIFAS { get; set; }
        public virtual DbSet<TIPO_RECOGIDAS> TIPO_RECOGIDAS { get; set; }
        public virtual DbSet<USUARIO_CIUDADES> USUARIO_CIUDADES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<DISTANCIAS> DISTANCIAS { get; set; }
    }
}
